const path = require('path');
const { app } = require(path.resolve('src', 'config', 'app'));
const swaggerAutogen = require('swagger-autogen')();

const outputFile = './swagger_output.json';
const endpointsFiles = [
    './src/routes/web.js',
    './src/routes/api.js'
];

const doc = {
    info: {
        version: '1.0.0',
        title: app.name,
        description: 'Documentation automatically generated by the <b>swagger.autogen</b> module.'
    },
    host: app.url,
    basePath: '/',
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            'name': 'Autenticação',
            'description': 'Endpoints'
        },
        {
            'name': 'Estudante',
            'description': 'Endpoints'
        },
        {
            'name': 'Professor',
            'description': 'Endpoints'
        },
        {
            'name': 'Curso',
            'description': 'Endpoints'
        },
        {
            'name': 'Matéria',
            'description': 'Endpoints'
        },
        {
            'name': 'Coordenador de Curso',
            'description': 'Endpoints'
        }
    ]
};

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./src/public/index.js');
});
