version: "3.8"
services:
    mysql_db:
        image: mysql:5.7
        ports:
            - "3307:3306"
        command: --default-authentication-plugin=mysql_native_password
        environment:
            MYSQL_DATABASE: myDb
            MYSQL_USER: user
            MYSQL_PASSWORD: test
            MYSQL_ROOT_PASSWORD: test
        volumes:
            - ./dump:/docker-entrypoint-initdb.d
            - ./conf:/etc/mysql/conf.d
            - persistent:/var/lib/mysql
        networks:
            - default
    application:
        depends_on:
            - mysql_db
        build: .
        ports:
            - "8001:80"
        volumes:
            - ./www:/var/www/html
        links:
            - db
        networks:
            - default
volumes:
    persistent:
